# Generated by Django 3.2.9 on 2021-11-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.TextField(choices=[('#1', 'active'), ('#2', 'is done'), ('#3', 'freeze')], default='#1'),
        ),
    ]
